log_dir: "/workspace/modeling/tts/PitchExtractor/Checkpoint"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: ""
train_data: "/workspace/modeling/tts/data/params/train-mix.txt"
val_data: "/workspace/modeling/tts/data/params/val-mix.txt"
num_workers: 16

  
optimizer_params:
  lr: 0.0003
  
loss_params:
  lambda_f0: 0.1
  
